# all: iris gear

# iris:
# 	@./run $@ 1
# 	@./run $@ 5
# 	@./run $@ 10
# 	@./run $@ 15
# 	@./run $@ 20
# 	@./run $@ 30
# 	@./run $@ 50
# 	@./run $@ 100

# gear:
# 	@./run $@ 1
# 	@./run $@ 5
# 	@./run $@ 10
# 	@./run $@ 15
# 	@./run $@ 20
# 	@./run $@ 30
# 	@./run $@ 50
# 	@./run $@ 100

# .PHONY: all iris gear
